name: WDIO Continuous Integration
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Chromiun
        run: sudo apt-get install chromium-browser
      - uses: actions/checkout@v2.7.0
      - name: Use Node.js
        uses: actions/setup-node@v3.6.0
        with:
          node-version: latest
      - run: npm install
        name: Install dependencies
      - run: npm run test
        name: Running E2E tests
      - uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: logs
          path: logs
